[package]
name = "erfa-sys"
version = "0.1.0"
authors = ["Sam Morrell <samuelmorrell@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]

[build-dependencies]
"bindgen" = "0.49.0"
"cc" = "1.0"
"glob" = "0.3.0"
regex = "1"
