/* automatically generated by rust-bindgen */

pub const ERFA_DPI: f64 = 3.141592653589793;
pub const ERFA_D2PI: f64 = 6.283185307179586;
pub const ERFA_DR2D: f64 = 57.29577951308232;
pub const ERFA_DR2AS: f64 = 206264.80624709636;
pub const ERFA_TURNAS: f64 = 1296000.0;
pub const ERFA_DTY: f64 = 365.242198781;
pub const ERFA_DAYSEC: f64 = 86400.0;
pub const ERFA_DJY: f64 = 365.25;
pub const ERFA_DJC: f64 = 36525.0;
pub const ERFA_DJM: f64 = 365250.0;
pub const ERFA_DJ00: f64 = 2451545.0;
pub const ERFA_DJM0: f64 = 2400000.5;
pub const ERFA_DJM00: f64 = 51544.5;
pub const ERFA_DJM77: f64 = 43144.0;
pub const ERFA_TTMTAI: f64 = 32.184;
pub const ERFA_CMPS: f64 = 299792458.0;
pub const ERFA_WGS84: u32 = 1;
pub const ERFA_GRS80: u32 = 2;
pub const ERFA_WGS72: u32 = 3;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct eraASTROM {
    pub pmt: f64,
    pub eb: [f64; 3usize],
    pub eh: [f64; 3usize],
    pub em: f64,
    pub v: [f64; 3usize],
    pub bm1: f64,
    pub bpn: [[f64; 3usize]; 3usize],
    pub along: f64,
    pub phi: f64,
    pub xpl: f64,
    pub ypl: f64,
    pub sphi: f64,
    pub cphi: f64,
    pub diurab: f64,
    pub eral: f64,
    pub refa: f64,
    pub refb: f64,
}
#[test]
fn bindgen_test_layout_eraASTROM() {
    assert_eq!(
        ::std::mem::size_of::<eraASTROM>(),
        248usize,
        concat!("Size of: ", stringify!(eraASTROM))
    );
    assert_eq!(
        ::std::mem::align_of::<eraASTROM>(),
        8usize,
        concat!("Alignment of ", stringify!(eraASTROM))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraASTROM>())).pmt as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(eraASTROM),
            "::",
            stringify!(pmt)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraASTROM>())).eb as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(eraASTROM),
            "::",
            stringify!(eb)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraASTROM>())).eh as *const _ as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(eraASTROM),
            "::",
            stringify!(eh)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraASTROM>())).em as *const _ as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(eraASTROM),
            "::",
            stringify!(em)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraASTROM>())).v as *const _ as usize },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(eraASTROM),
            "::",
            stringify!(v)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraASTROM>())).bm1 as *const _ as usize },
        88usize,
        concat!(
            "Offset of field: ",
            stringify!(eraASTROM),
            "::",
            stringify!(bm1)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraASTROM>())).bpn as *const _ as usize },
        96usize,
        concat!(
            "Offset of field: ",
            stringify!(eraASTROM),
            "::",
            stringify!(bpn)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraASTROM>())).along as *const _ as usize },
        168usize,
        concat!(
            "Offset of field: ",
            stringify!(eraASTROM),
            "::",
            stringify!(along)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraASTROM>())).phi as *const _ as usize },
        176usize,
        concat!(
            "Offset of field: ",
            stringify!(eraASTROM),
            "::",
            stringify!(phi)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraASTROM>())).xpl as *const _ as usize },
        184usize,
        concat!(
            "Offset of field: ",
            stringify!(eraASTROM),
            "::",
            stringify!(xpl)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraASTROM>())).ypl as *const _ as usize },
        192usize,
        concat!(
            "Offset of field: ",
            stringify!(eraASTROM),
            "::",
            stringify!(ypl)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraASTROM>())).sphi as *const _ as usize },
        200usize,
        concat!(
            "Offset of field: ",
            stringify!(eraASTROM),
            "::",
            stringify!(sphi)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraASTROM>())).cphi as *const _ as usize },
        208usize,
        concat!(
            "Offset of field: ",
            stringify!(eraASTROM),
            "::",
            stringify!(cphi)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraASTROM>())).diurab as *const _ as usize },
        216usize,
        concat!(
            "Offset of field: ",
            stringify!(eraASTROM),
            "::",
            stringify!(diurab)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraASTROM>())).eral as *const _ as usize },
        224usize,
        concat!(
            "Offset of field: ",
            stringify!(eraASTROM),
            "::",
            stringify!(eral)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraASTROM>())).refa as *const _ as usize },
        232usize,
        concat!(
            "Offset of field: ",
            stringify!(eraASTROM),
            "::",
            stringify!(refa)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraASTROM>())).refb as *const _ as usize },
        240usize,
        concat!(
            "Offset of field: ",
            stringify!(eraASTROM),
            "::",
            stringify!(refb)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct eraLDBODY {
    pub bm: f64,
    pub dl: f64,
    pub pv: [[f64; 3usize]; 2usize],
}
#[test]
fn bindgen_test_layout_eraLDBODY() {
    assert_eq!(
        ::std::mem::size_of::<eraLDBODY>(),
        64usize,
        concat!("Size of: ", stringify!(eraLDBODY))
    );
    assert_eq!(
        ::std::mem::align_of::<eraLDBODY>(),
        8usize,
        concat!("Alignment of ", stringify!(eraLDBODY))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraLDBODY>())).bm as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(eraLDBODY),
            "::",
            stringify!(bm)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraLDBODY>())).dl as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(eraLDBODY),
            "::",
            stringify!(dl)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<eraLDBODY>())).pv as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(eraLDBODY),
            "::",
            stringify!(pv)
        )
    );
}
extern "C" {
    #[link_name = "\u{1}_eraCal2jd"]
    pub fn eraCal2jd(
        iy: ::std::os::raw::c_int,
        im: ::std::os::raw::c_int,
        id: ::std::os::raw::c_int,
        djm0: *mut f64,
        djm: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraEpb"]
    pub fn eraEpb(dj1: f64, dj2: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraEpb2jd"]
    pub fn eraEpb2jd(epb: f64, djm0: *mut f64, djm: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraEpj"]
    pub fn eraEpj(dj1: f64, dj2: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraEpj2jd"]
    pub fn eraEpj2jd(epj: f64, djm0: *mut f64, djm: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraJd2cal"]
    pub fn eraJd2cal(
        dj1: f64,
        dj2: f64,
        iy: *mut ::std::os::raw::c_int,
        im: *mut ::std::os::raw::c_int,
        id: *mut ::std::os::raw::c_int,
        fd: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraJdcalf"]
    pub fn eraJdcalf(
        ndp: ::std::os::raw::c_int,
        dj1: f64,
        dj2: f64,
        iymdf: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraAb"]
    pub fn eraAb(pnat: *mut f64, v: *mut f64, s: f64, bm1: f64, ppr: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraApcg"]
    pub fn eraApcg(
        date1: f64,
        date2: f64,
        ebpv: *mut [f64; 3usize],
        ehp: *mut f64,
        astrom: *mut eraASTROM,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraApcg13"]
    pub fn eraApcg13(date1: f64, date2: f64, astrom: *mut eraASTROM);
}
extern "C" {
    #[link_name = "\u{1}_eraApci"]
    pub fn eraApci(
        date1: f64,
        date2: f64,
        ebpv: *mut [f64; 3usize],
        ehp: *mut f64,
        x: f64,
        y: f64,
        s: f64,
        astrom: *mut eraASTROM,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraApci13"]
    pub fn eraApci13(date1: f64, date2: f64, astrom: *mut eraASTROM, eo: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraApco"]
    pub fn eraApco(
        date1: f64,
        date2: f64,
        ebpv: *mut [f64; 3usize],
        ehp: *mut f64,
        x: f64,
        y: f64,
        s: f64,
        theta: f64,
        elong: f64,
        phi: f64,
        hm: f64,
        xp: f64,
        yp: f64,
        sp: f64,
        refa: f64,
        refb: f64,
        astrom: *mut eraASTROM,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraApco13"]
    pub fn eraApco13(
        utc1: f64,
        utc2: f64,
        dut1: f64,
        elong: f64,
        phi: f64,
        hm: f64,
        xp: f64,
        yp: f64,
        phpa: f64,
        tc: f64,
        rh: f64,
        wl: f64,
        astrom: *mut eraASTROM,
        eo: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraApcs"]
    pub fn eraApcs(
        date1: f64,
        date2: f64,
        pv: *mut [[f64; 2usize]; 3usize],
        ebpv: *mut [[f64; 2usize]; 3usize],
        ehp: *mut [f64; 3usize],
        astrom: *mut eraASTROM,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraApcs13"]
    pub fn eraApcs13(date1: f64, date2: f64, pv: *mut [f64; 3usize], astrom: *mut eraASTROM);
}
extern "C" {
    #[link_name = "\u{1}_eraAper"]
    pub fn eraAper(theta: f64, astrom: *mut eraASTROM);
}
extern "C" {
    #[link_name = "\u{1}_eraAper13"]
    pub fn eraAper13(ut11: f64, ut12: f64, astrom: *mut eraASTROM);
}
extern "C" {
    #[link_name = "\u{1}_eraApio"]
    pub fn eraApio(
        sp: f64,
        theta: f64,
        elong: f64,
        phi: f64,
        hm: f64,
        xp: f64,
        yp: f64,
        refa: f64,
        refb: f64,
        astrom: *mut eraASTROM,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraApio13"]
    pub fn eraApio13(
        utc1: f64,
        utc2: f64,
        dut1: f64,
        elong: f64,
        phi: f64,
        hm: f64,
        xp: f64,
        yp: f64,
        phpa: f64,
        tc: f64,
        rh: f64,
        wl: f64,
        astrom: *mut eraASTROM,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraAtci13"]
    pub fn eraAtci13(
        rc: f64,
        dc: f64,
        pr: f64,
        pd: f64,
        px: f64,
        rv: f64,
        date1: f64,
        date2: f64,
        ri: *mut f64,
        di: *mut f64,
        eo: *mut f64,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraAtciq"]
    pub fn eraAtciq(
        rc: f64,
        dc: f64,
        pr: f64,
        pd: f64,
        px: f64,
        rv: f64,
        astrom: *mut eraASTROM,
        ri: *mut f64,
        di: *mut f64,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraAtciqn"]
    pub fn eraAtciqn(
        rc: f64,
        dc: f64,
        pr: f64,
        pd: f64,
        px: f64,
        rv: f64,
        astrom: *mut eraASTROM,
        n: ::std::os::raw::c_int,
        b: *mut eraLDBODY,
        ri: *mut f64,
        di: *mut f64,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraAtciqz"]
    pub fn eraAtciqz(rc: f64, dc: f64, astrom: *mut eraASTROM, ri: *mut f64, di: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraAtco13"]
    pub fn eraAtco13(
        rc: f64,
        dc: f64,
        pr: f64,
        pd: f64,
        px: f64,
        rv: f64,
        utc1: f64,
        utc2: f64,
        dut1: f64,
        elong: f64,
        phi: f64,
        hm: f64,
        xp: f64,
        yp: f64,
        phpa: f64,
        tc: f64,
        rh: f64,
        wl: f64,
        aob: *mut f64,
        zob: *mut f64,
        hob: *mut f64,
        dob: *mut f64,
        rob: *mut f64,
        eo: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraAtic13"]
    pub fn eraAtic13(
        ri: f64,
        di: f64,
        date1: f64,
        date2: f64,
        rc: *mut f64,
        dc: *mut f64,
        eo: *mut f64,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraAticq"]
    pub fn eraAticq(ri: f64, di: f64, astrom: *mut eraASTROM, rc: *mut f64, dc: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraAticqn"]
    pub fn eraAticqn(
        ri: f64,
        di: f64,
        astrom: *mut eraASTROM,
        n: ::std::os::raw::c_int,
        b: *mut eraLDBODY,
        rc: *mut f64,
        dc: *mut f64,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraAtio13"]
    pub fn eraAtio13(
        ri: f64,
        di: f64,
        utc1: f64,
        utc2: f64,
        dut1: f64,
        elong: f64,
        phi: f64,
        hm: f64,
        xp: f64,
        yp: f64,
        phpa: f64,
        tc: f64,
        rh: f64,
        wl: f64,
        aob: *mut f64,
        zob: *mut f64,
        hob: *mut f64,
        dob: *mut f64,
        rob: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraAtioq"]
    pub fn eraAtioq(
        ri: f64,
        di: f64,
        astrom: *mut eraASTROM,
        aob: *mut f64,
        zob: *mut f64,
        hob: *mut f64,
        dob: *mut f64,
        rob: *mut f64,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraAtoc13"]
    pub fn eraAtoc13(
        type_: *const ::std::os::raw::c_char,
        ob1: f64,
        ob2: f64,
        utc1: f64,
        utc2: f64,
        dut1: f64,
        elong: f64,
        phi: f64,
        hm: f64,
        xp: f64,
        yp: f64,
        phpa: f64,
        tc: f64,
        rh: f64,
        wl: f64,
        rc: *mut f64,
        dc: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraAtoi13"]
    pub fn eraAtoi13(
        type_: *const ::std::os::raw::c_char,
        ob1: f64,
        ob2: f64,
        utc1: f64,
        utc2: f64,
        dut1: f64,
        elong: f64,
        phi: f64,
        hm: f64,
        xp: f64,
        yp: f64,
        phpa: f64,
        tc: f64,
        rh: f64,
        wl: f64,
        ri: *mut f64,
        di: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraAtoiq"]
    pub fn eraAtoiq(
        type_: *const ::std::os::raw::c_char,
        ob1: f64,
        ob2: f64,
        astrom: *mut eraASTROM,
        ri: *mut f64,
        di: *mut f64,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraLd"]
    pub fn eraLd(bm: f64, p: *mut f64, q: *mut f64, e: *mut f64, em: f64, dlim: f64, p1: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraLdn"]
    pub fn eraLdn(
        n: ::std::os::raw::c_int,
        b: *mut eraLDBODY,
        ob: *mut f64,
        sc: *mut f64,
        sn: *mut f64,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraLdsun"]
    pub fn eraLdsun(p: *mut f64, e: *mut f64, em: f64, p1: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraPmpx"]
    pub fn eraPmpx(
        rc: f64,
        dc: f64,
        pr: f64,
        pd: f64,
        px: f64,
        rv: f64,
        pmt: f64,
        pob: *mut f64,
        pco: *mut f64,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraPmsafe"]
    pub fn eraPmsafe(
        ra1: f64,
        dec1: f64,
        pmr1: f64,
        pmd1: f64,
        px1: f64,
        rv1: f64,
        ep1a: f64,
        ep1b: f64,
        ep2a: f64,
        ep2b: f64,
        ra2: *mut f64,
        dec2: *mut f64,
        pmr2: *mut f64,
        pmd2: *mut f64,
        px2: *mut f64,
        rv2: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraPvtob"]
    pub fn eraPvtob(
        elong: f64,
        phi: f64,
        height: f64,
        xp: f64,
        yp: f64,
        sp: f64,
        theta: f64,
        pv: *mut [f64; 3usize],
    );
}
extern "C" {
    #[link_name = "\u{1}_eraRefco"]
    pub fn eraRefco(phpa: f64, tc: f64, rh: f64, wl: f64, refa: *mut f64, refb: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraEpv00"]
    pub fn eraEpv00(
        date1: f64,
        date2: f64,
        pvh: *mut [f64; 3usize],
        pvb: *mut [f64; 3usize],
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraPlan94"]
    pub fn eraPlan94(
        date1: f64,
        date2: f64,
        np: ::std::os::raw::c_int,
        pv: *mut [f64; 3usize],
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraFad03"]
    pub fn eraFad03(t: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraFae03"]
    pub fn eraFae03(t: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraFaf03"]
    pub fn eraFaf03(t: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraFaju03"]
    pub fn eraFaju03(t: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraFal03"]
    pub fn eraFal03(t: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraFalp03"]
    pub fn eraFalp03(t: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraFama03"]
    pub fn eraFama03(t: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraFame03"]
    pub fn eraFame03(t: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraFane03"]
    pub fn eraFane03(t: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraFaom03"]
    pub fn eraFaom03(t: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraFapa03"]
    pub fn eraFapa03(t: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraFasa03"]
    pub fn eraFasa03(t: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraFaur03"]
    pub fn eraFaur03(t: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraFave03"]
    pub fn eraFave03(t: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraBi00"]
    pub fn eraBi00(dpsibi: *mut f64, depsbi: *mut f64, dra: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraBp00"]
    pub fn eraBp00(
        date1: f64,
        date2: f64,
        rb: *mut [f64; 3usize],
        rp: *mut [f64; 3usize],
        rbp: *mut [f64; 3usize],
    );
}
extern "C" {
    #[link_name = "\u{1}_eraBp06"]
    pub fn eraBp06(
        date1: f64,
        date2: f64,
        rb: *mut [f64; 3usize],
        rp: *mut [f64; 3usize],
        rbp: *mut [f64; 3usize],
    );
}
extern "C" {
    #[link_name = "\u{1}_eraBpn2xy"]
    pub fn eraBpn2xy(rbpn: *mut [f64; 3usize], x: *mut f64, y: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraC2i00a"]
    pub fn eraC2i00a(date1: f64, date2: f64, rc2i: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraC2i00b"]
    pub fn eraC2i00b(date1: f64, date2: f64, rc2i: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraC2i06a"]
    pub fn eraC2i06a(date1: f64, date2: f64, rc2i: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraC2ibpn"]
    pub fn eraC2ibpn(date1: f64, date2: f64, rbpn: *mut [f64; 3usize], rc2i: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraC2ixy"]
    pub fn eraC2ixy(date1: f64, date2: f64, x: f64, y: f64, rc2i: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraC2ixys"]
    pub fn eraC2ixys(x: f64, y: f64, s: f64, rc2i: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraC2t00a"]
    pub fn eraC2t00a(
        tta: f64,
        ttb: f64,
        uta: f64,
        utb: f64,
        xp: f64,
        yp: f64,
        rc2t: *mut [f64; 3usize],
    );
}
extern "C" {
    #[link_name = "\u{1}_eraC2t00b"]
    pub fn eraC2t00b(
        tta: f64,
        ttb: f64,
        uta: f64,
        utb: f64,
        xp: f64,
        yp: f64,
        rc2t: *mut [f64; 3usize],
    );
}
extern "C" {
    #[link_name = "\u{1}_eraC2t06a"]
    pub fn eraC2t06a(
        tta: f64,
        ttb: f64,
        uta: f64,
        utb: f64,
        xp: f64,
        yp: f64,
        rc2t: *mut [f64; 3usize],
    );
}
extern "C" {
    #[link_name = "\u{1}_eraC2tcio"]
    pub fn eraC2tcio(
        rc2i: *mut [f64; 3usize],
        era: f64,
        rpom: *mut [f64; 3usize],
        rc2t: *mut [f64; 3usize],
    );
}
extern "C" {
    #[link_name = "\u{1}_eraC2teqx"]
    pub fn eraC2teqx(
        rbpn: *mut [f64; 3usize],
        gst: f64,
        rpom: *mut [f64; 3usize],
        rc2t: *mut [f64; 3usize],
    );
}
extern "C" {
    #[link_name = "\u{1}_eraC2tpe"]
    pub fn eraC2tpe(
        tta: f64,
        ttb: f64,
        uta: f64,
        utb: f64,
        dpsi: f64,
        deps: f64,
        xp: f64,
        yp: f64,
        rc2t: *mut [f64; 3usize],
    );
}
extern "C" {
    #[link_name = "\u{1}_eraC2txy"]
    pub fn eraC2txy(
        tta: f64,
        ttb: f64,
        uta: f64,
        utb: f64,
        x: f64,
        y: f64,
        xp: f64,
        yp: f64,
        rc2t: *mut [f64; 3usize],
    );
}
extern "C" {
    #[link_name = "\u{1}_eraEo06a"]
    pub fn eraEo06a(date1: f64, date2: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraEors"]
    pub fn eraEors(rnpb: *mut [f64; 3usize], s: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraFw2m"]
    pub fn eraFw2m(gamb: f64, phib: f64, psi: f64, eps: f64, r: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraFw2xy"]
    pub fn eraFw2xy(gamb: f64, phib: f64, psi: f64, eps: f64, x: *mut f64, y: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraLtp"]
    pub fn eraLtp(epj: f64, rp: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraLtpb"]
    pub fn eraLtpb(epj: f64, rpb: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraLtpecl"]
    pub fn eraLtpecl(epj: f64, vec: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraLtpequ"]
    pub fn eraLtpequ(epj: f64, veq: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraNum00a"]
    pub fn eraNum00a(date1: f64, date2: f64, rmatn: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraNum00b"]
    pub fn eraNum00b(date1: f64, date2: f64, rmatn: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraNum06a"]
    pub fn eraNum06a(date1: f64, date2: f64, rmatn: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraNumat"]
    pub fn eraNumat(epsa: f64, dpsi: f64, deps: f64, rmatn: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraNut00a"]
    pub fn eraNut00a(date1: f64, date2: f64, dpsi: *mut f64, deps: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraNut00b"]
    pub fn eraNut00b(date1: f64, date2: f64, dpsi: *mut f64, deps: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraNut06a"]
    pub fn eraNut06a(date1: f64, date2: f64, dpsi: *mut f64, deps: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraNut80"]
    pub fn eraNut80(date1: f64, date2: f64, dpsi: *mut f64, deps: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraNutm80"]
    pub fn eraNutm80(date1: f64, date2: f64, rmatn: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraObl06"]
    pub fn eraObl06(date1: f64, date2: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraObl80"]
    pub fn eraObl80(date1: f64, date2: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraP06e"]
    pub fn eraP06e(
        date1: f64,
        date2: f64,
        eps0: *mut f64,
        psia: *mut f64,
        oma: *mut f64,
        bpa: *mut f64,
        bqa: *mut f64,
        pia: *mut f64,
        bpia: *mut f64,
        epsa: *mut f64,
        chia: *mut f64,
        za: *mut f64,
        zetaa: *mut f64,
        thetaa: *mut f64,
        pa: *mut f64,
        gam: *mut f64,
        phi: *mut f64,
        psi: *mut f64,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraPb06"]
    pub fn eraPb06(date1: f64, date2: f64, bzeta: *mut f64, bz: *mut f64, btheta: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraPfw06"]
    pub fn eraPfw06(
        date1: f64,
        date2: f64,
        gamb: *mut f64,
        phib: *mut f64,
        psib: *mut f64,
        epsa: *mut f64,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraPmat00"]
    pub fn eraPmat00(date1: f64, date2: f64, rbp: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraPmat06"]
    pub fn eraPmat06(date1: f64, date2: f64, rbp: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraPmat76"]
    pub fn eraPmat76(date1: f64, date2: f64, rmatp: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraPn00"]
    pub fn eraPn00(
        date1: f64,
        date2: f64,
        dpsi: f64,
        deps: f64,
        epsa: *mut f64,
        rb: *mut [f64; 3usize],
        rp: *mut [f64; 3usize],
        rbp: *mut [f64; 3usize],
        rn: *mut [f64; 3usize],
        rbpn: *mut [f64; 3usize],
    );
}
extern "C" {
    #[link_name = "\u{1}_eraPn00a"]
    pub fn eraPn00a(
        date1: f64,
        date2: f64,
        dpsi: *mut f64,
        deps: *mut f64,
        epsa: *mut f64,
        rb: *mut [f64; 3usize],
        rp: *mut [f64; 3usize],
        rbp: *mut [f64; 3usize],
        rn: *mut [f64; 3usize],
        rbpn: *mut [f64; 3usize],
    );
}
extern "C" {
    #[link_name = "\u{1}_eraPn00b"]
    pub fn eraPn00b(
        date1: f64,
        date2: f64,
        dpsi: *mut f64,
        deps: *mut f64,
        epsa: *mut f64,
        rb: *mut [f64; 3usize],
        rp: *mut [f64; 3usize],
        rbp: *mut [f64; 3usize],
        rn: *mut [f64; 3usize],
        rbpn: *mut [f64; 3usize],
    );
}
extern "C" {
    #[link_name = "\u{1}_eraPn06"]
    pub fn eraPn06(
        date1: f64,
        date2: f64,
        dpsi: f64,
        deps: f64,
        epsa: *mut f64,
        rb: *mut [f64; 3usize],
        rp: *mut [f64; 3usize],
        rbp: *mut [f64; 3usize],
        rn: *mut [f64; 3usize],
        rbpn: *mut [f64; 3usize],
    );
}
extern "C" {
    #[link_name = "\u{1}_eraPn06a"]
    pub fn eraPn06a(
        date1: f64,
        date2: f64,
        dpsi: *mut f64,
        deps: *mut f64,
        epsa: *mut f64,
        rb: *mut [f64; 3usize],
        rp: *mut [f64; 3usize],
        rbp: *mut [f64; 3usize],
        rn: *mut [f64; 3usize],
        rbpn: *mut [f64; 3usize],
    );
}
extern "C" {
    #[link_name = "\u{1}_eraPnm00a"]
    pub fn eraPnm00a(date1: f64, date2: f64, rbpn: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraPnm00b"]
    pub fn eraPnm00b(date1: f64, date2: f64, rbpn: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraPnm06a"]
    pub fn eraPnm06a(date1: f64, date2: f64, rnpb: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraPnm80"]
    pub fn eraPnm80(date1: f64, date2: f64, rmatpn: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraPom00"]
    pub fn eraPom00(xp: f64, yp: f64, sp: f64, rpom: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraPr00"]
    pub fn eraPr00(date1: f64, date2: f64, dpsipr: *mut f64, depspr: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraPrec76"]
    pub fn eraPrec76(
        date01: f64,
        date02: f64,
        date11: f64,
        date12: f64,
        zeta: *mut f64,
        z: *mut f64,
        theta: *mut f64,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraS00"]
    pub fn eraS00(date1: f64, date2: f64, x: f64, y: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraS00a"]
    pub fn eraS00a(date1: f64, date2: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraS00b"]
    pub fn eraS00b(date1: f64, date2: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraS06"]
    pub fn eraS06(date1: f64, date2: f64, x: f64, y: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraS06a"]
    pub fn eraS06a(date1: f64, date2: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraSp00"]
    pub fn eraSp00(date1: f64, date2: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraXy06"]
    pub fn eraXy06(date1: f64, date2: f64, x: *mut f64, y: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraXys00a"]
    pub fn eraXys00a(date1: f64, date2: f64, x: *mut f64, y: *mut f64, s: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraXys00b"]
    pub fn eraXys00b(date1: f64, date2: f64, x: *mut f64, y: *mut f64, s: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraXys06a"]
    pub fn eraXys06a(date1: f64, date2: f64, x: *mut f64, y: *mut f64, s: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraEe00"]
    pub fn eraEe00(date1: f64, date2: f64, epsa: f64, dpsi: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraEe00a"]
    pub fn eraEe00a(date1: f64, date2: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraEe00b"]
    pub fn eraEe00b(date1: f64, date2: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraEe06a"]
    pub fn eraEe06a(date1: f64, date2: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraEect00"]
    pub fn eraEect00(date1: f64, date2: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraEqeq94"]
    pub fn eraEqeq94(date1: f64, date2: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraEra00"]
    pub fn eraEra00(dj1: f64, dj2: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraGmst00"]
    pub fn eraGmst00(uta: f64, utb: f64, tta: f64, ttb: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraGmst06"]
    pub fn eraGmst06(uta: f64, utb: f64, tta: f64, ttb: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraGmst82"]
    pub fn eraGmst82(dj1: f64, dj2: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraGst00a"]
    pub fn eraGst00a(uta: f64, utb: f64, tta: f64, ttb: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraGst00b"]
    pub fn eraGst00b(uta: f64, utb: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraGst06"]
    pub fn eraGst06(uta: f64, utb: f64, tta: f64, ttb: f64, rnpb: *mut [f64; 3usize]) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraGst06a"]
    pub fn eraGst06a(uta: f64, utb: f64, tta: f64, ttb: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraGst94"]
    pub fn eraGst94(uta: f64, utb: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraPvstar"]
    pub fn eraPvstar(
        pv: *mut [f64; 3usize],
        ra: *mut f64,
        dec: *mut f64,
        pmr: *mut f64,
        pmd: *mut f64,
        px: *mut f64,
        rv: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraStarpv"]
    pub fn eraStarpv(
        ra: f64,
        dec: f64,
        pmr: f64,
        pmd: f64,
        px: f64,
        rv: f64,
        pv: *mut [f64; 3usize],
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraFk52h"]
    pub fn eraFk52h(
        r5: f64,
        d5: f64,
        dr5: f64,
        dd5: f64,
        px5: f64,
        rv5: f64,
        rh: *mut f64,
        dh: *mut f64,
        drh: *mut f64,
        ddh: *mut f64,
        pxh: *mut f64,
        rvh: *mut f64,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraFk5hip"]
    pub fn eraFk5hip(r5h: *mut [f64; 3usize], s5h: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraFk5hz"]
    pub fn eraFk5hz(r5: f64, d5: f64, date1: f64, date2: f64, rh: *mut f64, dh: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraH2fk5"]
    pub fn eraH2fk5(
        rh: f64,
        dh: f64,
        drh: f64,
        ddh: f64,
        pxh: f64,
        rvh: f64,
        r5: *mut f64,
        d5: *mut f64,
        dr5: *mut f64,
        dd5: *mut f64,
        px5: *mut f64,
        rv5: *mut f64,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraHfk5z"]
    pub fn eraHfk5z(
        rh: f64,
        dh: f64,
        date1: f64,
        date2: f64,
        r5: *mut f64,
        d5: *mut f64,
        dr5: *mut f64,
        dd5: *mut f64,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraStarpm"]
    pub fn eraStarpm(
        ra1: f64,
        dec1: f64,
        pmr1: f64,
        pmd1: f64,
        px1: f64,
        rv1: f64,
        ep1a: f64,
        ep1b: f64,
        ep2a: f64,
        ep2b: f64,
        ra2: *mut f64,
        dec2: *mut f64,
        pmr2: *mut f64,
        pmd2: *mut f64,
        px2: *mut f64,
        rv2: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraEceq06"]
    pub fn eraEceq06(date1: f64, date2: f64, dl: f64, db: f64, dr: *mut f64, dd: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraEcm06"]
    pub fn eraEcm06(date1: f64, date2: f64, rm: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraEqec06"]
    pub fn eraEqec06(date1: f64, date2: f64, dr: f64, dd: f64, dl: *mut f64, db: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraLteceq"]
    pub fn eraLteceq(epj: f64, dl: f64, db: f64, dr: *mut f64, dd: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraLtecm"]
    pub fn eraLtecm(epj: f64, rm: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraLteqec"]
    pub fn eraLteqec(epj: f64, dr: f64, dd: f64, dl: *mut f64, db: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraG2icrs"]
    pub fn eraG2icrs(dl: f64, db: f64, dr: *mut f64, dd: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraIcrs2g"]
    pub fn eraIcrs2g(dr: f64, dd: f64, dl: *mut f64, db: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraEform"]
    pub fn eraEform(n: ::std::os::raw::c_int, a: *mut f64, f: *mut f64) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraGc2gd"]
    pub fn eraGc2gd(
        n: ::std::os::raw::c_int,
        xyz: *mut f64,
        elong: *mut f64,
        phi: *mut f64,
        height: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraGc2gde"]
    pub fn eraGc2gde(
        a: f64,
        f: f64,
        xyz: *mut f64,
        elong: *mut f64,
        phi: *mut f64,
        height: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraGd2gc"]
    pub fn eraGd2gc(
        n: ::std::os::raw::c_int,
        elong: f64,
        phi: f64,
        height: f64,
        xyz: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraGd2gce"]
    pub fn eraGd2gce(
        a: f64,
        f: f64,
        elong: f64,
        phi: f64,
        height: f64,
        xyz: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraD2dtf"]
    pub fn eraD2dtf(
        scale: *const ::std::os::raw::c_char,
        ndp: ::std::os::raw::c_int,
        d1: f64,
        d2: f64,
        iy: *mut ::std::os::raw::c_int,
        im: *mut ::std::os::raw::c_int,
        id: *mut ::std::os::raw::c_int,
        ihmsf: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraDat"]
    pub fn eraDat(
        iy: ::std::os::raw::c_int,
        im: ::std::os::raw::c_int,
        id: ::std::os::raw::c_int,
        fd: f64,
        deltat: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraDtdb"]
    pub fn eraDtdb(date1: f64, date2: f64, ut: f64, elong: f64, u: f64, v: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraDtf2d"]
    pub fn eraDtf2d(
        scale: *const ::std::os::raw::c_char,
        iy: ::std::os::raw::c_int,
        im: ::std::os::raw::c_int,
        id: ::std::os::raw::c_int,
        ihr: ::std::os::raw::c_int,
        imn: ::std::os::raw::c_int,
        sec: f64,
        d1: *mut f64,
        d2: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraTaitt"]
    pub fn eraTaitt(tai1: f64, tai2: f64, tt1: *mut f64, tt2: *mut f64) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraTaiut1"]
    pub fn eraTaiut1(
        tai1: f64,
        tai2: f64,
        dta: f64,
        ut11: *mut f64,
        ut12: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraTaiutc"]
    pub fn eraTaiutc(tai1: f64, tai2: f64, utc1: *mut f64, utc2: *mut f64)
        -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraTcbtdb"]
    pub fn eraTcbtdb(tcb1: f64, tcb2: f64, tdb1: *mut f64, tdb2: *mut f64)
        -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraTcgtt"]
    pub fn eraTcgtt(tcg1: f64, tcg2: f64, tt1: *mut f64, tt2: *mut f64) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraTdbtcb"]
    pub fn eraTdbtcb(tdb1: f64, tdb2: f64, tcb1: *mut f64, tcb2: *mut f64)
        -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraTdbtt"]
    pub fn eraTdbtt(
        tdb1: f64,
        tdb2: f64,
        dtr: f64,
        tt1: *mut f64,
        tt2: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraTttai"]
    pub fn eraTttai(tt1: f64, tt2: f64, tai1: *mut f64, tai2: *mut f64) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraTttcg"]
    pub fn eraTttcg(tt1: f64, tt2: f64, tcg1: *mut f64, tcg2: *mut f64) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraTttdb"]
    pub fn eraTttdb(
        tt1: f64,
        tt2: f64,
        dtr: f64,
        tdb1: *mut f64,
        tdb2: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraTtut1"]
    pub fn eraTtut1(
        tt1: f64,
        tt2: f64,
        dt: f64,
        ut11: *mut f64,
        ut12: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraUt1tai"]
    pub fn eraUt1tai(
        ut11: f64,
        ut12: f64,
        dta: f64,
        tai1: *mut f64,
        tai2: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraUt1tt"]
    pub fn eraUt1tt(
        ut11: f64,
        ut12: f64,
        dt: f64,
        tt1: *mut f64,
        tt2: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraUt1utc"]
    pub fn eraUt1utc(
        ut11: f64,
        ut12: f64,
        dut1: f64,
        utc1: *mut f64,
        utc2: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraUtctai"]
    pub fn eraUtctai(utc1: f64, utc2: f64, tai1: *mut f64, tai2: *mut f64)
        -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraUtcut1"]
    pub fn eraUtcut1(
        utc1: f64,
        utc2: f64,
        dut1: f64,
        ut11: *mut f64,
        ut12: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraA2af"]
    pub fn eraA2af(
        ndp: ::std::os::raw::c_int,
        angle: f64,
        sign: *mut ::std::os::raw::c_char,
        idmsf: *mut ::std::os::raw::c_int,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraA2tf"]
    pub fn eraA2tf(
        ndp: ::std::os::raw::c_int,
        angle: f64,
        sign: *mut ::std::os::raw::c_char,
        ihmsf: *mut ::std::os::raw::c_int,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraAf2a"]
    pub fn eraAf2a(
        s: ::std::os::raw::c_char,
        ideg: ::std::os::raw::c_int,
        iamin: ::std::os::raw::c_int,
        asec: f64,
        rad: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraAnp"]
    pub fn eraAnp(a: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraAnpm"]
    pub fn eraAnpm(a: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraD2tf"]
    pub fn eraD2tf(
        ndp: ::std::os::raw::c_int,
        days: f64,
        sign: *mut ::std::os::raw::c_char,
        ihmsf: *mut ::std::os::raw::c_int,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraTf2a"]
    pub fn eraTf2a(
        s: ::std::os::raw::c_char,
        ihour: ::std::os::raw::c_int,
        imin: ::std::os::raw::c_int,
        sec: f64,
        rad: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraTf2d"]
    pub fn eraTf2d(
        s: ::std::os::raw::c_char,
        ihour: ::std::os::raw::c_int,
        imin: ::std::os::raw::c_int,
        sec: f64,
        days: *mut f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraRx"]
    pub fn eraRx(phi: f64, r: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraRy"]
    pub fn eraRy(theta: f64, r: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraRz"]
    pub fn eraRz(psi: f64, r: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraCp"]
    pub fn eraCp(p: *mut f64, c: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraCpv"]
    pub fn eraCpv(pv: *mut [f64; 3usize], c: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraCr"]
    pub fn eraCr(r: *mut [f64; 3usize], c: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraP2pv"]
    pub fn eraP2pv(p: *mut f64, pv: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraPv2p"]
    pub fn eraPv2p(pv: *mut [f64; 3usize], p: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraIr"]
    pub fn eraIr(r: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraZp"]
    pub fn eraZp(p: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraZpv"]
    pub fn eraZpv(pv: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraZr"]
    pub fn eraZr(r: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraRxr"]
    pub fn eraRxr(a: *mut [f64; 3usize], b: *mut [f64; 3usize], atb: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraTr"]
    pub fn eraTr(r: *mut [f64; 3usize], rt: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraRxp"]
    pub fn eraRxp(r: *mut [f64; 3usize], p: *mut f64, rp: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraRxpv"]
    pub fn eraRxpv(r: *mut [f64; 3usize], pv: *mut [f64; 3usize], rpv: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraTrxp"]
    pub fn eraTrxp(r: *mut [f64; 3usize], p: *mut f64, trp: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraTrxpv"]
    pub fn eraTrxpv(r: *mut [f64; 3usize], pv: *mut [f64; 3usize], trpv: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraRm2v"]
    pub fn eraRm2v(r: *mut [f64; 3usize], w: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraRv2m"]
    pub fn eraRv2m(w: *mut f64, r: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraPap"]
    pub fn eraPap(a: *mut f64, b: *mut f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraPas"]
    pub fn eraPas(al: f64, ap: f64, bl: f64, bp: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraSepp"]
    pub fn eraSepp(a: *mut f64, b: *mut f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraSeps"]
    pub fn eraSeps(al: f64, ap: f64, bl: f64, bp: f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraC2s"]
    pub fn eraC2s(p: *mut f64, theta: *mut f64, phi: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraP2s"]
    pub fn eraP2s(p: *mut f64, theta: *mut f64, phi: *mut f64, r: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraPv2s"]
    pub fn eraPv2s(
        pv: *mut [f64; 3usize],
        theta: *mut f64,
        phi: *mut f64,
        r: *mut f64,
        td: *mut f64,
        pd: *mut f64,
        rd: *mut f64,
    );
}
extern "C" {
    #[link_name = "\u{1}_eraS2c"]
    pub fn eraS2c(theta: f64, phi: f64, c: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraS2p"]
    pub fn eraS2p(theta: f64, phi: f64, r: f64, p: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraS2pv"]
    pub fn eraS2pv(theta: f64, phi: f64, r: f64, td: f64, pd: f64, rd: f64, pv: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraPdp"]
    pub fn eraPdp(a: *mut f64, b: *mut f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraPm"]
    pub fn eraPm(p: *mut f64) -> f64;
}
extern "C" {
    #[link_name = "\u{1}_eraPmp"]
    pub fn eraPmp(a: *mut f64, b: *mut f64, amb: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraPn"]
    pub fn eraPn(p: *mut f64, r: *mut f64, u: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraPpp"]
    pub fn eraPpp(a: *mut f64, b: *mut f64, apb: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraPpsp"]
    pub fn eraPpsp(a: *mut f64, s: f64, b: *mut f64, apsb: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraPvdpv"]
    pub fn eraPvdpv(a: *mut [f64; 3usize], b: *mut [f64; 3usize], adb: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraPvm"]
    pub fn eraPvm(pv: *mut [f64; 3usize], r: *mut f64, s: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraPvmpv"]
    pub fn eraPvmpv(a: *mut [f64; 3usize], b: *mut [f64; 3usize], amb: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraPvppv"]
    pub fn eraPvppv(a: *mut [f64; 3usize], b: *mut [f64; 3usize], apb: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraPvu"]
    pub fn eraPvu(dt: f64, pv: *mut [f64; 3usize], upv: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraPvup"]
    pub fn eraPvup(dt: f64, pv: *mut [f64; 3usize], p: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraPvxpv"]
    pub fn eraPvxpv(a: *mut [f64; 3usize], b: *mut [f64; 3usize], axb: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraPxp"]
    pub fn eraPxp(a: *mut f64, b: *mut f64, axb: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraS2xpv"]
    pub fn eraS2xpv(s1: f64, s2: f64, pv: *mut [f64; 3usize], spv: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraSxp"]
    pub fn eraSxp(s: f64, p: *mut f64, sp: *mut f64);
}
extern "C" {
    #[link_name = "\u{1}_eraSxpv"]
    pub fn eraSxpv(s: f64, pv: *mut [f64; 3usize], spv: *mut [f64; 3usize]);
}
extern "C" {
    #[link_name = "\u{1}_eraVersion"]
    pub fn eraVersion() -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[link_name = "\u{1}_eraVersionMajor"]
    pub fn eraVersionMajor() -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraVersionMinor"]
    pub fn eraVersionMinor() -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraVersionMicro"]
    pub fn eraVersionMicro() -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_eraSofaVersion"]
    pub fn eraSofaVersion() -> *const ::std::os::raw::c_char;
}
