[package]
name = "tesys_astrometry"
version = "0.1.0"
authors = ["Sam Morrell <samuelmorrell@gmail.com>"]
edition = "2018"

[dependencies]
erfa-sys = { path = "src/erfa-sys/" }
chrono = "*"
nalgebra = "*"